version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Twitter
  app:
    image: twitter
    container_name: twitter
    ports:
      - '4000:3000'
    depends_on:
        - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MSQL_DATABASE=Twitter